---
name: pep8
on: [pull_request, push]
env:
  PYTHON_VERSION: "3.12.4"
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ¬ Triggered by ${{ github.event_name }}."
      - run: echo "ğŸ§ Running on ${{ runner.os }}."
      - run: echo "â¬‡ï¸ Cloning ${{ github.repository }}:${{ github.ref_name }}â€¦"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ Setting up Python $PYTHON_VERSIONâ€¦"
      - run: "$PYTHON_VERSION"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "$PYTHON_VERSION"
      - run: echo "ğŸ” Linting Python code against PEP 8â€¦"
      - name: Lint Python code against PEP 8
        uses: py-actions/flake8@v2
...
